# Generated by Django 4.1 on 2022-08-16 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0002_remove_shorturl_unique_url_shorturl_unique_url_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='short_url',
            new_name='slug',
        ),
    ]
